/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated.forbidden'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated.records'
import { Route as AuthenticatedAuditDocumentsRouteImport } from './routes/_authenticated/audit/documents'
import { Route as AuthenticatedAuditTransactionsRouteImport } from './routes/_authenticated/audit/transactions'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/_authenticated/documents/$documentId'
import { Route as AuthenticatedDocumentsMineRouteImport } from './routes/_authenticated/documents/mine'
import { Route as AuthenticatedDocumentsNewRouteImport } from './routes/_authenticated/documents/new'
import { Route as AuthenticatedDocumentsSearchRouteImport } from './routes/_authenticated/documents/search'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditDocumentsRoute =
  AuthenticatedAuditDocumentsRouteImport.update({
    id: '/audit/documents',
    path: '/audit/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditTransactionsRoute =
  AuthenticatedAuditTransactionsRouteImport.update({
    id: '/audit/transactions',
    path: '/audit/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsMineRoute =
  AuthenticatedDocumentsMineRouteImport.update({
    id: '/documents/mine',
    path: '/documents/mine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsNewRoute =
  AuthenticatedDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsSearchRoute =
  AuthenticatedDocumentsSearchRouteImport.update({
    id: '/documents/search',
    path: '/documents/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/audit/documents': typeof AuthenticatedAuditDocumentsRoute
  '/audit/transactions': typeof AuthenticatedAuditTransactionsRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/documents/mine': typeof AuthenticatedDocumentsMineRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/documents/search': typeof AuthenticatedDocumentsSearchRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/': typeof AuthenticatedIndexRoute
  '/audit/documents': typeof AuthenticatedAuditDocumentsRoute
  '/audit/transactions': typeof AuthenticatedAuditTransactionsRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/documents/mine': typeof AuthenticatedDocumentsMineRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/documents/search': typeof AuthenticatedDocumentsSearchRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/audit/documents': typeof AuthenticatedAuditDocumentsRoute
  '/_authenticated/audit/transactions': typeof AuthenticatedAuditTransactionsRoute
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/_authenticated/documents/mine': typeof AuthenticatedDocumentsMineRoute
  '/_authenticated/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/_authenticated/documents/search': typeof AuthenticatedDocumentsSearchRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/forbidden'
    | '/records'
    | '/audit/documents'
    | '/audit/transactions'
    | '/documents/$documentId'
    | '/documents/mine'
    | '/documents/new'
    | '/documents/search'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/forbidden'
    | '/records'
    | '/'
    | '/audit/documents'
    | '/audit/transactions'
    | '/documents/$documentId'
    | '/documents/mine'
    | '/documents/new'
    | '/documents/search'
    | '/documents'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/forbidden'
    | '/_authenticated/records'
    | '/_authenticated/'
    | '/_authenticated/audit/documents'
    | '/_authenticated/audit/transactions'
    | '/_authenticated/documents/$documentId'
    | '/_authenticated/documents/mine'
    | '/_authenticated/documents/new'
    | '/_authenticated/documents/search'
    | '/_authenticated/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/documents': {
      id: '/_authenticated/audit/documents'
      path: '/audit/documents'
      fullPath: '/audit/documents'
      preLoaderRoute: typeof AuthenticatedAuditDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/transactions': {
      id: '/_authenticated/audit/transactions'
      path: '/audit/transactions'
      fullPath: '/audit/transactions'
      preLoaderRoute: typeof AuthenticatedAuditTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/mine': {
      id: '/_authenticated/documents/mine'
      path: '/documents/mine'
      fullPath: '/documents/mine'
      preLoaderRoute: typeof AuthenticatedDocumentsMineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/new': {
      id: '/_authenticated/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthenticatedDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/search': {
      id: '/_authenticated/documents/search'
      path: '/documents/search'
      fullPath: '/documents/search'
      preLoaderRoute: typeof AuthenticatedDocumentsSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuditDocumentsRoute: typeof AuthenticatedAuditDocumentsRoute
  AuthenticatedAuditTransactionsRoute: typeof AuthenticatedAuditTransactionsRoute
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
  AuthenticatedDocumentsMineRoute: typeof AuthenticatedDocumentsMineRoute
  AuthenticatedDocumentsNewRoute: typeof AuthenticatedDocumentsNewRoute
  AuthenticatedDocumentsSearchRoute: typeof AuthenticatedDocumentsSearchRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuditDocumentsRoute: AuthenticatedAuditDocumentsRoute,
  AuthenticatedAuditTransactionsRoute: AuthenticatedAuditTransactionsRoute,
  AuthenticatedDocumentsDocumentIdRoute: AuthenticatedDocumentsDocumentIdRoute,
  AuthenticatedDocumentsMineRoute: AuthenticatedDocumentsMineRoute,
  AuthenticatedDocumentsNewRoute: AuthenticatedDocumentsNewRoute,
  AuthenticatedDocumentsSearchRoute: AuthenticatedDocumentsSearchRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
